"""add_price_refresh_status

Revision ID: 7202881a0dca
Revises: d0e1f2a3b4c5
Create Date: 2026-04-03 17:25:47.307945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7202881a0dca'
down_revision: Union[str, Sequence[str], None] = 'd0e1f2a3b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_refresh_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store', postgresql.ENUM('COLES', 'WOOLWORTHS', name='store', create_type=False), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('total_products', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('unavailable_count', sa.Integer(), nullable=False),
    sa.Column('not_found_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store', name='uq_price_refresh_status_store')
    )
    op.create_index(op.f('ix_price_refresh_status_store'), 'price_refresh_status', ['store'], unique=False)
    op.create_index(op.f('ix_store_cookies_user_id'), 'store_cookies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_cookies_user_id'), table_name='store_cookies')
    op.drop_index(op.f('ix_price_refresh_status_store'), table_name='price_refresh_status')
    op.drop_table('price_refresh_status')
    # ### end Alembic commands ###
