"""initial schema

Revision ID: 815267ccee89
Revises: 
Create Date: 2026-03-17 15:30:40.118142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815267ccee89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store', sa.Enum('COLES', 'WOOLWORTHS', name='store'), nullable=False),
    sa.Column('store_order_id', sa.String(length=64), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('store_name', sa.String(length=256), nullable=True),
    sa.Column('store_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_order_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store', sa.Enum('COLES', 'WOOLWORTHS', name='store'), nullable=False),
    sa.Column('store_product_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('brand', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.Column('unit_size', sa.String(length=64), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('unit_price_measure', sa.String(length=32), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('product_url', sa.String(length=1024), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store', 'store_product_id', name='uq_store_product')
    )
    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'ORDERED', name='liststatus'), nullable=False),
    sa.Column('preferred_store', sa.Enum('COLES', 'WOOLWORTHS', name='store'), nullable=True),
    sa.Column('estimated_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_cookies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store', sa.Enum('COLES', 'WOOLWORTHS', name='store'), nullable=False),
    sa.Column('cookies_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_cookies_store'), 'store_cookies', ['store'], unique=True)
    op.create_table('consumption_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('avg_purchase_interval_days', sa.Float(), nullable=False),
    sa.Column('avg_quantity_per_purchase', sa.Float(), nullable=False),
    sa.Column('estimated_daily_consumption', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('last_purchased_date', sa.Date(), nullable=False),
    sa.Column('predicted_runout_date', sa.Date(), nullable=False),
    sa.Column('next_purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_count', sa.Integer(), nullable=False),
    sa.Column('last_purchase_quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_purchase_store', sa.String(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_paid', sa.Float(), nullable=False),
    sa.Column('was_substituted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store', sa.Enum('COLES', 'WOOLWORTHS', name='store'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_a_id', sa.Integer(), nullable=False),
    sa.Column('product_b_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('match_method', sa.String(length=32), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_rejected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_a_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_b_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_a_id', 'product_b_id', name='uq_product_match')
    )
    op.create_table('shopping_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopping_list_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('coles_price', sa.Float(), nullable=True),
    sa.Column('woolworths_price', sa.Float(), nullable=True),
    sa.Column('chosen_store', sa.Enum('COLES', 'WOOLWORTHS', name='store'), nullable=True),
    sa.Column('is_user_added', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('is_ordered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_list_items')
    op.drop_table('product_matches')
    op.drop_table('price_history')
    op.drop_table('order_items')
    op.drop_table('consumption_predictions')
    op.drop_index(op.f('ix_store_cookies_store'), table_name='store_cookies')
    op.drop_table('store_cookies')
    op.drop_table('shopping_lists')
    op.drop_table('products')
    op.drop_table('orders')
    # ### end Alembic commands ###
